update github action

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -14,17 +14,28 @@ jobs:
     steps:
     - name: Checkout code
       uses: actions/checkout@v4
-      
+
     - name: Set up Python
       uses: actions/setup-python@v3
       with:
-        python-version: '3.10'  # You can specify any version you need
-        
+        python-version: '3.10'  # Specify the Python version you need
+
     - name: Install Pylint
       run: |
         python -m pip install --upgrade pip
         python -m pip install pylint
-        
+
     - name: Run Pylint on all Python files
+      id: pylint
       run: |
-        pylint **/*.py || true  # This allows the workflow to continue even if pylint finds issues
+        pylint_output=$(pylint **/*.py)
+        echo "$pylint_output"
+
+        # Extract the score from the pylint output
+        score=$(echo "$pylint_output" | grep "Your code has been rated" | awk '{print $7}' | sed 's|/10||')
+
+        # Check if the score is below the threshold
+        if (( $(echo "$score < 10" | bc -l) )); then
+            echo "Pylint score is below the threshold of 5.0. Failing the job."
+            exit 1
+        fi
